### ISSUE TITLE
PWA: cache and download

### ISSUE THREAD

**Issue by qtipee** [HE-Arc/pwa-playlist-generator#16]
**Cache** : using the service workers to cache specific audio files or folders, so that it is then possible to listen to these files without an Internet connection.

**Download** : download specific audio files or folders to the user file system.

**Comment by qtipee** [comment]
Promises are used to cache/download specific files.

When a folder needs to be cached/downloaded, its content is recursively cached/downloaded the same way as a specific file for each of its files.

**Comment by qtipee** [comment]
Easy for caching a folder ; just iterate over its content and call the function to cache a specific file for each file.

But for downloading a folder, the zip generation must wait for every promise (fetch) to complete via Promise.all([promises]) ; otherwise, the zip archive is empty !

**Comment by qtipee** [comment]
Recursively downloading a folder is now implemented.

Need to implement the fetching of an asset file - before the generation of the PWA zip file - in order to avoid putting the CSS/JS files in a string in the template.js script ; the design template creation will then be easier.

**Comment by grunenwald** [comment]
👍

**Comment by qtipee** [comment]
It is now possible to fetch asset files from the server and to add them to a zip. This functionality is used in the PWA zip file generation to add the default JavaScript files for example.

This functionality can be used to add all the necessary asset files for a specific template ; but need to define which files are to fetch based on the selected template.

**Comment by qtipee** [comment]
The caching of a specific file for offline listening is still functional, but it does not work when caching a folder ; need to investigate in the application caches content in detail.

**Comment by qtipee** [comment]
The service workers have been reviewed and the caching is now fully functional. For now, there are two caches :

- STATIC_CACHE_NAME : contains the application index and assets (css, js, images, ...)
- AUDIO_CACHE_NAME : contains the audio files that have been selected to be cached

Note : in order to refresh the caches, you have to manually modify the name of the above constants in the « service-workers.js » file ; the « activate » event deletes a cache if its name differs.
